Tratamiento_Variables:
  Replicar:
    - frec_alcohol_audit
    - puntaje_audit
    - Palabras_moca
    - memoria_moca
    - puntaje_moca
    - sexo
    - edo_civil
    - personas_hogar
    - nivel_e
    - trabajo
    - ejercicio
    - af_trabajo
    - af_libre
    - cafe
    - tipo_dieta
    - tabaco
    - alcohol
    - tipo_alcohol
    - frec_alcohol
    - alergias_alim
    - horas_sueño
    - horas_sueño_fs
    - descansa
    - siesta
    - cambios_apetito
    - cambios_sueño
    - int_quirugica
    - covid
    - fam_cardiacos
    - fam_acvascular
    - fam_obesidad
    - fam_diabetes
    - fam_colesterol
    - fam_hta
    - fam_enfgastro
    - aspirina
    - otras_med
    - tranquilizantes
    - vitaminas
    - suplementos
    - prebioticos
  Rellenar_Cercano:
    - pcr
    - glucosa
    - bun
    - creatinina
    - filtrado_glomerular
    - ac_urico
    - col_total
    - trigliceridos
    - asat
    - alat
    - ggt
    - bilirrubina_total
    - fosfatasa_alcalina
    - ldh
    - proteinas_totales
    - albumina
    - amilasa
    - lipasa
    - sodio
    - potasio
    - cloro
    - calcio
    - fosforo
    - magnesio
    - hierro
    - densidad_orina
    - ph_orina
    - hemoglobina_orina
    - leucocitos_orina
    - nitritos_orina
    - albumina_orina
    - bilirrubina_orina
    - cetonas_orina
    - urobilinogeno_orina
    - glucosa_orina
    - hematies_sed
    - leucocitos_sed
    - bacterias_sed
    - celulas_epiteliales_sed
    - cilindros_hialinos_sed
    - precipitados_urat_sed
    - oxalato_calcico_sed
    - fibra_mucoide_sed
    - creatinina_orina
    - albumina_orina_num
    - indice_albumina_creatinina
    - albumina_porcentaje
    - alfa1_globulina
    - alfa2_globulina
    - beta_globulina
    - gamma_globulina
    - indice_albumina_globulinas
    - prealbumina
    - ferritina
    - transferrina
    - capacidad_ligar_hierro
    - saturacion_transferrina
    - col_ldl
    - col_hdl
    - apolipoproteina_a1
    - apolipoproteina_b
    - homocisteina_basal
    - ac_folico_intraeritrocitos
    - vit_b12
    - ac_folico_serico
    - selenio
    - zinc
    - cobre
    - leucocitos
    - hematies
    - hemoglobina
    - hematocrito
    - vcm
    - hcm
    - chcm
    - ade
    - neutrofilos_porcentaje
    - eosinofilos_porcentaje
    - basofilos_porcentaje
    - linfocitos_porcentaje
    - monocitos_porcentaje
    - neutrofilos
    - eosinofilos
    - basofilos
    - linfocitos
    - monocitos
    - vsg
    - hemoglobina_glicada
    - tiempo_protrombina_porcentaje
    - tiempo_protrombina
    - inr
    - tiempo_protrombina_rati
    - tiempo_tromboplastina
    - tiempo_tromboplastina_rati
    - fibrinogeno
    - tsh
    - t4
    - t3
    - cortisol
    - insulina
    - vit_d3
    - enf
    - antibioticos
    - medicamentos
    - bristol
    - PAS_izq
    - PAD_izq
    - PAS_der
    - PAD_der
    - peso
    - talla
    - imc
    - grasa
    - musculo
    - grasa_vic
    - tmb
    - tiempo_sedentario
    - af_ligera
    - af_mv
    - af_ligera_porcentaje
    - af_mv_procentaje
    - pasos_dia
    - eficiencia_sueño
    - min_cama
    - min_dormir
    - waso
    - num_despertares
    - duracion_despertares
    - ind_frag_sueño
    - ind_mov
    - ind_frag
    - ipaq_dias_int
    - ipaq_min_int
    - ipaq_dias_mod
    - ipaq_min_mod
    - ipaq_dias_cam
    - ipaq_min_cam
    - ipaq_horas_sent
    - ipaq_mets
    - ipaq_nivel_af
    - d2_con_pd
    - d2_con_pc
    - d2_con_pt
    - d2_vt_pd
    - d2_vt_pc
    - d2_vt_pt
    - d2_e_pd
    - d2_e_pc
    - d2_e_pt
    - d2_con1_pd
    - d2_con2_pd
    - d2_con3_pd
    - d2_con4_pd
    - wcst_años_educacion
    - wcst_cc_pd
    - wcst_cc_t
    - wcst_ep_pd
    - wcst_ep_t
    - wcst_te_pd
    - wcst_te_t
    - wcst_pp_pd
    - wcst_pp_t
    - wcst_ife_pd
    - wcst_ife_t
    - fn_cara
    - fn_letra
    - fn_nombre
    - ad_dietamed
    - ansiedad
    - depresion
    - pgh_h_acostarse
    - pgh_min_dormirse
    - pgh_h_levantarse
    - pgh_h_dormir
    - pgh_5a
    - pgh_5b
    - pgh_5c
    - pgh_5d
    - pgh_5e
    - pgh_5f
    - pgh_5g
    - pgh_5h
    - pgh_5i
    - pgh_calidad_sueño
    - pgh_med_dormir
    - pgh_somnolencias
    - pgh_tener_animos
    - pgh_compañia
    - pgh_compañia_a
    - pgh_compañia_b
    - pgh_compañia_c
    - pgh_compañia_d
    - ffq_panblanco
    - ffq_paninteg
    - ffq_cerealdes
    - ffq_muesli
    - ffq_arrozblan
    - ffq_arrozINT
    - ffq_pastaINT
    - ffq_espagueti
    - ffq_quinoa
    - ffq_lenteja
    - ffq_alubiaseca
    - ffq_garbanzos
    - ffq_guisantes
    - ffq_acelgas
    - ffq_coles
    - ffq_lechug
    - ffq_tomat
    - ffq_zanahor
    - ffq_jverde
    - ffq_calabacin
    - ffq_pimientos
    - ffq_esparragos
    - ffq_gazpach
    - ffq_otrasver
    - ffq_cebollas
    - ffq_ajos
    - ffq_seta
    - ffq_p_cocidas
    - ffq_p_fritascas
    - ffq_sofrito
    - ffq_naranjas
    - ffq_platanos
    - ffq_manzanas
    - ffq_fresa
    - ffq_cerezas
    - ffq_melocoton
    - ffq_sandi
    - ffq_kiwis
    - ffq_pina
    - ffq_uva
    - ffq_tropicales
    - ffq_almibar
    - ffq_pasas
    - ffq_almendras
    - ffq_avellanas
    - ffq_nuez
    - ffq_pistacho
    - ffq_semillas
    - ffq_leche_ent
    - ffq_leche_semi
    - ffq_leche_desn
    - ffq_leche_cond
    - ffq_bebidas_vegetales
    - ffq_yogur_ent
    - ffq_yogur_des
    - ffq_otros_lacteos
    - ffq_nata_crema
    - ffq_batidos
    - ffq_requeson
    - ffq_quesito
    - ffq_quesos
    - ffq_q_fresco
    - ffq_helados
    - ffq_huevos
    - ffq_p_blanco
    - ffq_p_azul
    - ffq_bacalao
    - ffq_almejas
    - ffq_calamar
    - ffq_crustaceos
    - ffq_p_aceite
    - ffq_p_natural
    - ffq_surimi
    - ffq_pollopiel
    - ffq_pollonopiel
    - ffq_c_ternera
    - ffq_c_cerdomagra
    - ffq_c_cerdonomagra
    - ffq_c_cordero
    - ffq_c_conejo
    - ffq_hamburguesa
    - ffq_bacon
    - ffq_higad
    - ffq_visceras
    - ffq_j_serrano
    - ffq_j_cocido
    - ffq_otros_embutidos
    - ffq_carnes_procesadas
    - ffq_pates
    - ffq_ac_oliva
    - ffq_ac_olivavir
    - ffq_ac_girasol
    - ffq_ac_maiz
    - ffq_aguacate
    - ffq_aceitunas
    - ffq_ac_mezcla
    - ffq_margarinas
    - ffq_mantequillas
    - ffq_mantecacer
    - ffq_g_maria
    - ffq_g_integral
    - ffq_g_sinazucar
    - ffq_g_choco
    - ffq_bizcocho
    - ffq_croissant
    - ffq_natilla
    - ffq_pastel
    - ffq_churro
    - ffq_turrones
    - ffq_chocolate_negro
    - ffq_chocolates
    - ffq_cacao
    - ffq_croquetas
    - ffq_sopasobre
    - ffq_mostaz
    - ffq_mayones
    - ffq_tomatefri
    - ffq_sal
    - ffq_mermeladas
    - ffq_mieles
    - ffq_azuc
    - ffq_edulcorantes
    - ffq_perejil
    - ffq_picante
    - ffq_p_fritascom
    - ffq_snack
    - ffq_tortitas
    - ffq_pizzas
    - ffq_agua
    - ffq_infusiones
    - ffq_refrescos
    - ffq_refrescsin
    - ffq_bebida_energetica
    - ffq_z_natural
    - ffq_z_frutasnat
    - ffq_z_botella
    - ffq_cafedesc
    - ffq_cafes
    - ffq_te
    - ffq_v_tintojov
    - ffq_v_tintoañej
    - ffq_v_blanco
    - ffq_v_rosado
    - ffq_cavas
    - ffq_cervezas
    - ffq_cerveza_sin
    - ffq_licores
    - ffq_whisky
    - ffq_hc
    - ffq_prot
    - ffq_protanim
    - ffq_protveg
    - ffq_grasa
    - ffq_alcohol
    - ffq_energiatot
    - ffq_ags
    - ffq_agm
    - ffq_agp
    - ffq_colesterol
    - ffq_azucares
    - ffq_fibra
    - ffq_polisacaridos
    - ffq_na
    - ffq_k
    - ffq_ca
    - ffq_mg
    - ffq_p
    - ffq_fe
    - ffq_zn
    - ffq_vit_a
    - ffq_retinoides
    - ffq_carotenoides
    - ffq_vit_d
    - ffq_vit_e
    - ffq_vit_b1
    - ffq_vit_b2
    - ffq_vit_b3
    - ffq_vit_b6
    - ffq_vit_b9
    - ffq_vit_b12
    - ffq_vit_c
    - luteina
    - zeaxantina
    - betacriptoxantina
    - alfacaroteno
    - betacaroteno
    - licopeno
    - licopeno_5cis
    - licopeno_trans
    - FC_media
    - cintura_media
    - cadera_media
    - cintura_cadera
    - homa_ir
    - fn_score
    - mortality_risk
    - phenoage
    - dif_crono_pheno
    - adherencia_lic
    - cv_percepcion_calidad_vida_100
    - cv_percepcion_salud_100
    - cv_physical_100
    - cv_psychological_100
    - cv_social_relationships_100
    - cv_enviroment_100
    - hads_score
    - pgh_latencia
    - horas_cama
    - pgh_por_eficiencia
    - pgh_eficiencia
    - pgh_perturbaciones
    - pgh_disfuncion_dia
    - pgh_duracion_sueño
    - pgh_total
    - cat_pgh_total
    - plaquetas
    - vol_plaquetario
  Eliminar:
    - f_inclusion
    - trabajo_otro
    - tipo_ejercicio
    - otra_dieta
    - Tipo_alergia
    - tipo_apetito
    - tipo_sueño
    - tipo_intervencion
    - tipo_cardiacos
    - tipo_acvascular
    - tipo_obesidad
    - tipo_diabetes
    - tipo_colesterol
    - tipo_hta
    - tipo_enfgastro
    - med1
    - med1_ruta
    - med1_dosis
    - med1_unidades
    - med1_vecesdia
    - med1_indicacion
    - med1_ inicio
    - med1_ final
    - med1_continua
    - med2
    - med2_ruta
    - med2_dosis
    - med2_unidades
    - med2_vecesdia
    - med2_indicacion
    - med2_ inicio
    - med2_ final
    - med2_continua
    - med3
    - med3_ruta
    - med3_dosis
    - med3_unidades
    - med3_vecesdia
    - med3_indicacion
    - med3_ inicio
    - med3_ final
    - med3_continua
    - med4
    - med4_ruta
    - med4_dosis
    - med4_unidades
    - med4_vecesdia
    - med4_indicacion
    - med4_ inicio
    - med4_ final
    - med4_continua
    - med5
    - med5_ruta
    - med5_dosis
    - med5_unidades
    - med5_vecesdia
    - med5_indicacion
    - med5_ inicio
    - med5_ final
    - med5_continua
    - med6
    - med6_ruta
    - med6_dosis
    - med6_unidades
    - med6_vecesdia
    - med6_indicacion
    - med6_ inicio
    - med6_ final
    - med6_continua
    - observaciones_hc
    - fecha_visita
    - fecha_extra
    - fecha_analitica
    - edad_analitica
    - bilirrubina_directa
    - bilirrubina_indirecta
    - sed_orina
    - amilasa_orina
    - col_ldl_directo
    - ccmh
    - hdw
    - macroocitos
    - microcitos
    - hematies_hipocromicos
    - pdw
    - luc_porcentaje
    - luc
    - anti_tpo
    - tipo_enf
    - med1_1
    - med1_ruta_1
    - med1_dosis_1
    - med1_unidades_1
    - med1_vecesdia_1
    - med1_indicacion_1
    - med1_ inicio_1
    - med1_ final_1
    - med1_continua_1
    - med2_1
    - med2_ruta_1
    - med2_dosis_1
    - med2_unidades_1
    - med2_vecesdia_1
    - med2_indicacion_1
    - med2_ inicio_1
    - med2_ final_1
    - med2_continua_1
    - med3_1
    - med3_ruta_1
    - med3_dosis_1
    - med3_unidades_1
    - med3_vecesdia_1
    - med3_indicacion_1
    - med3_ inicio_1
    - med3_ final_1
    - med3_continua_1
    - med4_1
    - med4_ruta_1
    - med4_dosis_1
    - med4_unidades_1
    - med4_vecesdia_1
    - med4_indicacion_1
    - med4_ inicio_1
    - med4_ final_1
    - med4_continua_1
    - FC1_izq
    - FC2_izq
    - FC3_izq
    - FC1_der
    - FC2_der
    - FC3_der
    - cintura1
    - cintura2
    - cintura3
    - cadera1
    - cadera2
    - cadera3
    - pgh_5j_especifica
    - ta_i5_t1_c1
    - ta_i7_t1_c1
    - tb_i9_t1_c1
    - PAS_media
    - PAD_media
    - xb
    - pgh_compañia_e
  Especial:
    - f_nac
    - med1
    - med2
    - med3
    - med4
    - med5
    - med6
    - ini_menst
    - fin_menst
    - num_depo
    - observaciones
    - pgh_5j
    - tom_dias
    - tom_momento
    - tom_aceite
    - tom_crudo
    - tom_cocido
    - tom_sofrito
    - tom_horno
    - tom_micro
    - tom_fa
    - tom_otro
    - tom_no
    - tom_completo
    - g_dia_tom
    - mg_dia_licopeno
  Cat_Temporales:
    - cv_p1
    - cv_p2
    - cv_p3
    - cv_p4
    - cv_p5
    - cv_p6
    - cv_p7
    - cv_p8
    - cv_p9
    - cv_p10
    - cv_p11
    - cv_p12
    - cv_p13
    - cv_p14
    - cv_p15
    - cv_p16
    - cv_p17
    - cv_p18
    - cv_p19
    - cv_p20
    - cv_p21
    - cv_p22
    - cv_p23
    - cv_p24
    - cv_p25
    - cv_p26
    - cv_percepcion_calidad_vida
    - cv_percepcion_salud
    - cv_physical
    - cv_psychological
    - cv_social_relationships
    - cv_enviroment
    - isi_1a
    - isi_1b
    - isi_1c
    - isi_2
    - isi_3
    - isi_4
    - isi_5
    - isi_total
  Objetivos:
    - bdnf
    - delta_bdnf
    - delta_d2_con_pd
    - delta_d2_vt_pd
    - delta_fn_nombre
    - delta_fn_score
    - delta_licopeno
Filtrado_Variables:
  Umbral_Varianza:
    - leucocitos_sed_(3-5)
    - hematies_sed_Moderado
    - leucocitos_sed_(25-30)
    - ffq_visceras
    - celulas_epiteliales_sed_Escaso
    - fibra_mucoide_sed_Ausente
    - oxalato_calcico_sed_Escaso
    - leucocitos_sed_(1-3)
    - trabajo
    - hematies_sed_(1-3)
    - leucocitos_sed_(5-10)
    - celulas_epiteliales_sed_Abundante
    - cetonas_orina
    - oxalato_calcico_sed_Negativo
    - tranquilizantes
    - hematies_sed_(1-5)
    - ffq_almibar
    - albumina_orina
    - leucocitos_sed_(100-150)
    - hematies_sed_(35-60)
    - ffq_leche_cond
    - aspirina
    - ffq_ac_maiz
    - bilirrubina_orina
    - hematies_sed_(25-30)
    - leucocitos_sed_(35-60)
    - nitritos_orina
    - glucosa_orina
  Correlacionadas:
    - PAS_der
    - PAS_izq
    - ffq_fe
    - ffq_mg
    - ffq_vit_b6
    - ffq_vit_b9
    - cv_physical_100
    - d2_con4_pd
    - d2_con3_pd
    - d2_con_pt
    - d2_con2_pd
    - d2_con_pc
    - d2_con1_pd
    - saturacion_transferrina
    - capacidad_ligar_hierro
    - d2_vt_pt
    - d2_vt_pc
    - tiempo_protrombina
    - tiempo_protrombina_rati
    - hemoglobina
    - min_dormir
    - ffq_grasa
    - ffq_p
    - ffq_zn
    - af_mv_procentaje
    - af_mv
    - cv_percepcion_salud_100
    - cv_percepcion_salud
    - PAD_izq
    - PAD_der
    - homa_ir
    - wcst_ife_t
    - cv_enviroment_100
    - ind_frag
    - mortality_risk
    - ffq_carotenoides
    - col_total
    - apolipoproteina_b
    - ansiedad
    - peso
    - tmb
    - g_dia_tom
    - d2_e_pt
    - d2_e_pc
    - wcst_ep_pd
    - waso
    - indice_albumina_globulinas
    - licopeno_trans
    - licopeno_5cis
    - wcst_te_pd
    - cv_psychological_100
    - pgh_h_dormir
    - cv_p1
    - cv_percepcion_calidad_vida_100
    - ffq_fibra
    - grasa
    - leucocitos
    - cv_social_relationships_100

# ---------------------
# Modelos Avance 4
# ---------------------
models_and_params:
  Ridge:
    model:
      class: Ridge
      params: {}
    param_grid:
      model__alpha: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
      model__solver: [svd, cholesky, lsqr, sag, saga]

  Lasso:
    model:
      class: Lasso
      params:
        max_iter: 20000
    param_grid:
      model__alpha: [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
      model__selection: [cyclic, random]

  ElasticNet:
    model:
      class: ElasticNet
      params:
        max_iter: 20000
    param_grid:
      model__alpha: [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0]
      model__l1_ratio: [0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99]

  SVR:
    model:
      class: SVR
      params: {}
    param_grid:
      model__kernel: [linear, poly, rbf, sigmoid]
      model__C: [0.01, 0.1, 1, 10, 100, 500]
      model__gamma: [scale, auto, 0.001, 0.01, 0.1]
      model__epsilon: [0.001, 0.01, 0.1, 0.2, 0.5]

  KNN Regressor:
    model:
      class: KNeighborsRegressor
      params: {}
    param_grid:
      model__n_neighbors: [3, 5, 7, 9, 11, 15, 21]
      model__weights: [uniform, distance]
      model__p: [1, 2]

  Decision Tree:
    model:
      class: DecisionTreeRegressor
      params:
        random_state: 42
    param_grid:
      model__max_depth: [null, 5, 10, 20, 50]
      model__min_samples_split: [2, 5, 10, 20]
      model__min_samples_leaf: [1, 2, 5, 10, 15]

  MLP Regressor:
    model:
      class: MLPRegressor
      params:
        max_iter: 5000
        random_state: 42
    param_grid:
      model__hidden_layer_sizes:
        - [50]
        - [100]
        - [50, 50]
        - [100, 50]
        - [100, 100]
      model__activation: [tanh, relu]
      model__solver: [lbfgs, adam]
      model__alpha: [0.0001, 0.001, 0.01, 0.1]

# ---------------------
# Modelos Final
# ---------------------
models_and_params_v2:
  Ridge:
    model:
      class: Ridge
      params: {}
    param_grid:
      model__alpha: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
      model__solver: [svd, cholesky, lsqr, sag, saga]

  Lasso:
    model:
      class: Lasso
      params:
        max_iter: 20000
    param_grid:
      model__alpha: [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
      model__selection: [cyclic, random]

  ElasticNet:
    model:
      class: ElasticNet
      params:
        max_iter: 20000
    param_grid:
      model__alpha: [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0]
      model__l1_ratio: [0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99]

  SVR:
    model:
      class: SVR
      params: {}
    param_grid:
      model__kernel: [linear, poly, rbf, sigmoid]
      model__C: [0.01, 0.1, 1, 10, 100, 500]
      model__gamma: [scale, auto, 0.001, 0.01, 0.1]
      model__epsilon: [0.001, 0.01, 0.1, 0.2, 0.5]

  KNN Regressor:
    model:
      class: KNeighborsRegressor
      params: {}
    param_grid:
      model__n_neighbors: [3, 5, 7, 9, 11, 15, 21]
      model__weights: [uniform, distance]
      model__p: [1, 2]

  Decision Tree:
    model:
      class: DecisionTreeRegressor
      params:
        random_state: 42
    param_grid:
      model__max_depth: [null, 5, 10, 20, 50]
      model__min_samples_split: [2, 5, 10, 20]
      model__min_samples_leaf: [1, 2, 5, 10, 15]
  
  "PLSRegression": {
        "model": {
            "class": "PLSRegression",
            "params": {
                # Se desactiva porque ya tienes StandardScaler en el Pipeline
                "scale": False 
            }
        },
        "param_grid": {
            # Búsqueda conservadora de variables latentes para evitar sobreajuste
            "model__n_components": [1, 2, 3, 4, 5, 6, 7] 
        }
    }